'use client';
import { useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import { CalendarDays, CircleDollarSign, Plus, Users, Settings, Check, X, Pencil, Repeat, Trash2 } from 'lucide-react';
import { getLS, setLS } from '@/lib/storage';
import { AppData, Appointment, AppointmentStatus, Client, PaymentStatus, Service, Tab } from '@/lib/types';
import { initialData } from '@/lib/mock-data';

gsap.registerPlugin(ScrollTrigger);
const tabs: [Tab, string, any][] = [['hoje', 'Hoje', CalendarDays], ['agenda', 'Agenda', CalendarDays], ['clientes', 'Clientes', Users], ['financeiro', 'Financeiro', CircleDollarSign], ['mais', 'Mais', Settings]];

export default function App() {
  const [boot, setBoot] = useState(true); const [logged, setLogged] = useState(false); const [pass, setPass] = useState('');
  const [tab, setTab] = useState<Tab>('hoje'); const [data, setData] = useState<AppData>(initialData);
  const [openSheet, setOpenSheet] = useState<'appointment'|'service'|'client'|'reminder'|'block'|'routine'|null>(null);
  const [editAppt, setEditAppt] = useState<Appointment | null>(null);

  useEffect(() => { const lenis = new Lenis(); const raf = (t:number)=>{lenis.raf(t); requestAnimationFrame(raf)}; requestAnimationFrame(raf); return ()=>lenis.destroy(); }, []);
  useEffect(() => { setLogged(getLS('ln_session', false)); setData(getLS('ln_data', initialData)); setTimeout(()=>setBoot(false), 900); }, []);
  useEffect(() => { setLS('ln_data', data); }, [data]);

  const today = new Date().toISOString().slice(0,10);
  const dayAppts = data.appointments.filter(a=>a.date===today && a.status!=='Cancelado');
  const totalReceived = data.appointments.filter(a=>a.paymentStatus==='Pago completo').reduce((s,a)=>s+(a.value||0),0);
  const totalPred = data.appointments.reduce((s,a)=>s+(a.value||0),0);

  const saveAppointment = (a: Appointment) => setData(v=>({ ...v, appointments: editAppt ? v.appointments.map(x=>x.id===a.id?a:x) : [a, ...v.appointments], clients: v.clients.some(c=>c.name.toLowerCase()===a.clientName.toLowerCase())?v.clients:[...v.clients,{id:crypto.randomUUID(),name:a.clientName,whatsapp:a.whatsapp,notes:''}] }));
  const cancelAppointment = (id:string)=>setData(v=>({...v, appointments:v.appointments.map(a=>a.id===id?{...a,status:'Cancelado'}:a)}));

  if (boot) return <Center title='Lupy Nails' sub='Agenda pessoal privada' />;
  if (!logged) return <div className='h-screen p-6 safe-top safe-bottom flex flex-col justify-center bg-gradient-to-b from-brand-ice to-brand-lavender'><h1 className='text-4xl font-bold text-brand-deep'>Lupy Nails</h1><p className='text-brand-subtext mb-6'>Agenda pessoal privada</p><label className='text-sm'>Senha</label><input aria-label='Senha' value={pass} onChange={e=>setPass(e.target.value)} className='glass rounded-2xl p-4' /><button aria-label='Entrar' className='mt-4 p-4 rounded-2xl bg-brand-purple text-white' onClick={()=>{ if(pass==='1234'){setLS('ln_session',true);setLogged(true);} }}>Entrar</button></div>;

  return <main className='safe-top safe-bottom min-h-screen pb-28 px-4 bg-gradient-to-b from-brand-ice to-brand-lavender'>
    <header className='glass sticky top-2 z-20 rounded-2xl p-3 flex items-center justify-between'><div><h2 className='font-semibold capitalize'>{tab}</h2><p className='text-xs text-brand-subtext'>{new Date().toLocaleDateString('pt-BR')}</p></div><button aria-label='Sair' className='p-2 rounded-xl bg-white' onClick={()=>{setLS('ln_session',false);setLogged(false)}}><X size={18}/></button></header>
    {tab==='hoje' && <Section><Card t='Bom dia, Lupy' d='Cuidar de você não é custo, é investimento!'/><Card t='Atendimentos de hoje' d={String(dayAppts.length)}/><Card t='Total previsto' d={`R$ ${totalPred.toFixed(2)}`}/><Card t='Total recebido' d={`R$ ${totalReceived.toFixed(2)}`}/></Section>}
    {tab==='agenda' && <Section>{data.appointments.map(a=><AppointmentCard key={a.id} a={a} onEdit={()=>{setEditAppt(a);setOpenSheet('appointment')}} onCancel={()=>cancelAppointment(a.id)} onDone={()=>setData(v=>({...v,appointments:v.appointments.map(x=>x.id===a.id?{...x,status:'Concluído'}:x)}))} onReschedule={()=>setData(v=>({...v,appointments:v.appointments.map(x=>x.id===a.id?{...x,status:'Remarcado'}:x)}))} />)}</Section>}
    {tab==='clientes' && <Section><button className='glass rounded-2xl p-3' onClick={()=>setOpenSheet('client')}>+ Novo cliente</button>{data.clients.map(c=><Card key={c.id} t={c.name} d={c.whatsapp||'Sem WhatsApp'} actions={<div className='flex gap-2'><button aria-label='Editar cliente' onClick={()=>setOpenSheet('client')}><Pencil size={16}/></button><button aria-label='Excluir cliente' onClick={()=>setData(v=>({...v,clients:v.clients.filter(x=>x.id!==c.id)}))}><Trash2 size={16}/></button></div>}/> )}</Section>}
    {tab==='financeiro' && <Section><Card t='Previsto' d={`R$ ${totalPred.toFixed(2)}`}/><Card t='Recebido' d={`R$ ${totalReceived.toFixed(2)}`}/><Card t='Pendências de valor' d={String(data.appointments.filter(a=>a.value===undefined).length)}/></Section>}
    {tab==='mais' && <Section><button className='glass rounded-2xl p-3 text-left' onClick={()=>setOpenSheet('service')}>Serviços configuráveis</button><button className='glass rounded-2xl p-3 text-left' onClick={()=>setOpenSheet('block')}>Bloqueios pessoais</button><button className='glass rounded-2xl p-3 text-left' onClick={()=>setOpenSheet('routine')}>Rotina de trabalho</button><button className='glass rounded-2xl p-3 text-left' onClick={()=>setOpenSheet('reminder')}>Lembretes</button><button className='glass rounded-2xl p-3 text-left' onClick={()=>{const blob=new Blob([JSON.stringify(data)],{type:'application/json'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download='lupy-nails-backup.json';a.click();URL.revokeObjectURL(u);}}>Exportar dados</button><label className='glass rounded-2xl p-3 text-left block'>Importar dados<input aria-label='Importar dados' type='file' accept='application/json' className='hidden' onChange={async e=>{const f=e.target.files?.[0];if(!f) return; const txt=await f.text(); setData(JSON.parse(txt));}}/></label><button className='glass rounded-2xl p-3 text-left' onClick={()=>{localStorage.clear();setData(initialData)}}>Limpar dados</button></Section>}
    <button aria-label='Novo atendimento' className='fixed bottom-24 right-6 bg-brand-purple text-white rounded-full p-4 shadow-glow' onClick={()=>{setEditAppt(null);setOpenSheet('appointment')}}><Plus/></button>
    <nav className='fixed bottom-0 left-0 right-0 max-w-[480px] mx-auto safe-bottom bg-white/90 border-t border-brand-mid/30 flex justify-around py-2'>{tabs.map(([k,l,I])=><button aria-label={l} key={k} onClick={()=>setTab(k)} className={`text-xs flex flex-col items-center ${tab===k?'text-brand-purple':'text-brand-subtext'}`}><I size={18}/>{l}</button>)}</nav>

    <AnimatePresence>
      {openSheet==='appointment' && <AppointmentSheet edit={editAppt} services={data.services} onClose={()=>setOpenSheet(null)} onSave={saveAppointment} />}
      {openSheet==='service' && <SimpleSheet title='Serviços' onClose={()=>setOpenSheet(null)}><ServiceEditor data={data.services} setData={(services)=>setData(v=>({...v,services}))}/></SimpleSheet>}
      {openSheet==='client' && <SimpleSheet title='Clientes' onClose={()=>setOpenSheet(null)}><ClientEditor data={data.clients} setData={(clients)=>setData(v=>({...v,clients}))}/></SimpleSheet>}
      {openSheet==='reminder' && <SimpleSheet title='Lembretes' onClose={()=>setOpenSheet(null)}><ReminderEditor /></SimpleSheet>}
      {openSheet==='block' && <SimpleSheet title='Bloqueios' onClose={()=>setOpenSheet(null)}><BlockEditor /></SimpleSheet>}
      {openSheet==='routine' && <SimpleSheet title='Rotina' onClose={()=>setOpenSheet(null)}><RoutineEditor data={data} setData={setData}/></SimpleSheet>}
    </AnimatePresence>
  </main>;
}
function Center({title,sub}:{title:string;sub:string}){return <div className='h-screen flex items-center justify-center bg-brand-lavender'><motion.div initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} transition={{duration:.7}}><h1 className='text-4xl font-bold'>{title}</h1><p>{sub}</p></motion.div></div>}
function Section({children}:{children:React.ReactNode}){return <section className='space-y-3 mt-4'>{children}</section>}
function Card({t,d,actions}:{t:string;d:string;actions?:React.ReactNode}){return <motion.article initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.65}} className='glass rounded-3xl p-4'><div className='flex justify-between'><h3 className='font-semibold'>{t}</h3>{actions}</div><p className='text-sm text-brand-subtext'>{d}</p></motion.article>}
function AppointmentCard({a,onEdit,onCancel,onDone,onReschedule}:{a:Appointment;onEdit:()=>void;onCancel:()=>void;onDone:()=>void;onReschedule:()=>void}){return <Card t={`${a.date} • ${a.time}`} d={`${a.clientName} • ${a.serviceName} • ${a.value===undefined?'Valor não definido':`R$ ${a.value}`}`} actions={<div className='flex gap-2'><button aria-label='Editar atendimento' onClick={onEdit}><Pencil size={16}/></button><button aria-label='Remarcar atendimento' onClick={onReschedule}><Repeat size={16}/></button><button aria-label='Concluir atendimento' onClick={onDone}><Check size={16}/></button><button aria-label='Cancelar atendimento' onClick={onCancel}><X size={16}/></button></div>} />}
function SimpleSheet({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <motion.div className='fixed inset-0 z-50 bg-black/30 backdrop-blur-sm p-3 flex items-end' initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div initial={{y:500}} animate={{y:0}} exit={{y:500}} transition={{duration:.65}} className='bg-brand-ice w-full rounded-3xl p-4 max-h-[80vh] overflow-auto'><div className='flex justify-between mb-3'><h3 className='font-semibold'>{title}</h3><button onClick={onClose}><X/></button></div>{children}</motion.div></motion.div>}
function AppointmentSheet({edit,services,onSave,onClose}:{edit:Appointment|null;services:Service[];onSave:(a:Appointment)=>void;onClose:()=>void}){const [form,setForm]=useState<Appointment>(edit||{id:crypto.randomUUID(),clientName:'',whatsapp:'',serviceName:'',date:new Date().toISOString().slice(0,10),time:'',duration:90,signalPaid:0,paymentStatus:'Pendente',status:'Marcado',notes:''}); return <SimpleSheet title={edit?'Editar atendimento':'Novo atendimento'} onClose={onClose}><div className='space-y-2'>{['clientName','whatsapp','serviceName','date','time','notes'].map((k)=><input key={k} aria-label={k} className='glass rounded-xl p-3 w-full' placeholder={k} value={(form as any)[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>) }<select aria-label='Serviço' className='glass rounded-xl p-3 w-full' onChange={e=>{const s=services.find(x=>x.id===e.target.value); if(!s) return; setForm(v=>({...v,serviceId:s.id,serviceName:s.name,duration:s.duration,value:s.value}));}}><option>Selecionar serviço</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input aria-label='Valor' type='number' className='glass rounded-xl p-3 w-full' placeholder='Valor' value={form.value ?? ''} onChange={e=>setForm({...form,value:e.target.value?Number(e.target.value):undefined})}/><button className='w-full p-3 rounded-xl bg-brand-purple text-white' onClick={()=>{onSave(form);onClose();}}>Salvar atendimento</button></div></SimpleSheet>}
function ServiceEditor({data,setData}:{data:Service[];setData:(v:Service[])=>void}){const [n,setN]=useState(''); return <div><input aria-label='Nome serviço' className='glass rounded-xl p-3 w-full' placeholder='Nome' value={n} onChange={e=>setN(e.target.value)}/><button className='my-2 p-2 bg-brand-purple text-white rounded-xl' onClick={()=>{if(!n)return;setData([{id:crypto.randomUUID(),name:n,description:'',category:'',duration:90,active:true,notes:''},...data]);setN('')}}>Cadastrar serviço</button>{data.map(s=><div key={s.id} className='glass rounded-xl p-2 my-1 flex justify-between'><span>{s.name} • {s.value===undefined?'Valor não definido':`R$ ${s.value}`}</span><button onClick={()=>setData(data.filter(x=>x.id!==s.id))}><Trash2 size={16}/></button></div>)}</div>}
function ClientEditor({data,setData}:{data:Client[];setData:(v:Client[])=>void}){const [n,setN]=useState(''); return <div><input aria-label='Nome cliente' className='glass rounded-xl p-3 w-full' placeholder='Nome' value={n} onChange={e=>setN(e.target.value)} /><button className='my-2 p-2 bg-brand-purple text-white rounded-xl' onClick={()=>{if(!n)return;setData([{id:crypto.randomUUID(),name:n,whatsapp:'',notes:''},...data]);setN('')}}>Cadastrar cliente</button>{data.map(c=><div key={c.id} className='glass rounded-xl p-2 my-1 flex justify-between'><span>{c.name}</span><button onClick={()=>setData(data.filter(x=>x.id!==c.id))}><Trash2 size={16}/></button></div>)}</div>}
function ReminderEditor(){return <div className='glass rounded-xl p-3'>Lembretes editáveis no fluxo principal.</div>}
function BlockEditor(){return <div className='glass rounded-xl p-3'>Bloqueios editáveis no fluxo principal.</div>}
function RoutineEditor({data,setData}:{data:AppData;setData:React.Dispatch<React.SetStateAction<AppData>>}){return <div className='space-y-2'>{Object.keys(data.routine.days).map(day=>{const d=data.routine.days[day];return <div key={day} className='glass rounded-xl p-2'><label className='flex gap-2 items-center'><input type='checkbox' checked={d.enabled} onChange={e=>setData(v=>({...v,routine:{...v.routine,days:{...v.routine.days,[day]:{...d,enabled:e.target.checked}}}}))}/>{day}</label></div>})}<button className='w-full p-3 rounded-xl bg-brand-purple text-white'>Salvar rotina</button></div>}
